apiVersion: v1
kind: Service
metadata:
  name: capital-markets-api
  namespace: ants-capital-markets
  labels:
    app: ants
    component: capital-markets-api
    flavor: capital-markets
    project: ants-capital-markets
  annotations:
    description: "Internal service for ANTS Capital Markets API"
spec:
  type: ClusterIP
  selector:
    app: ants
    component: capital-markets-api
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  sessionAffinity: None
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
